Enable configuration home
Enable the global --config flag.
Set the default value and start using
it on the build command

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -39,3 +39,10 @@ jobs:
             echo "Project does not build"
             exit 1
           fi
+
+      - name: Run tests
+        run: |
+          if ! go test ./... -v; then
+            echo "Project tests failed"
+            exit 1
+          fi
